# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

exclude: ^docs/

repos:
  # Standard hooks (yaml, eol, BOM, etc)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      -   id: check-yaml
      -   id: trailing-whitespace
      -   id: check-json
      -   id: check-symlinks
      -   id: check-xml
      -   id: fix-byte-order-marker
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: forbid-tabs

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Run mypy static type checking
  # disabled because of inconsistent results between the command line and pre-commit
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: v1.8.0
  #    hooks:
  #      -   id: mypy
  #          additional_dependencies: [imgui-bundle]
