"""Single 2D pixel coordinate as a Pydantic model.

Used as a single-point output (e.g. `minMaxLoc` result) and a
single-point input (e.g. `floodFill` seed). Pydantic gives us an
autogenerated edit form for free.
"""

from pydantic import BaseModel

from fiatlight.fiat_togui.gui_registry import base_model_with_gui_registration


@base_model_with_gui_registration()
class Point2D(BaseModel):
    """A single 2D pixel coordinate (integer x, y)."""

    x: int = 0
    y: int = 0
