@startuml

!include _p_fiat_core.puml
!include _p_to_gui.puml
!include _p_fiat_nodes.puml
!include _p_fiat_runner.puml

fiat_core.FunctionWithGui ...> to_gui.free_functions: uses add_input_outputs_to_function_with_gui

@enduml
